# Part 1 - Data Preprpcessing

## Importing Libaries

In [1]:
import numpy as np 
import pandas as pd 

import tensorflow as tf
from tensorflow import keras

from keras.models import Sequential
from keras.layers import Dense

In [2]:
dataset = pd.read_csv('../input/bank-data/bank_customers.csv')

In [3]:
dataset.head()

,CustomerID,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,Class1,fraud
0,15776156,1,22,11,2,4,4,1,0,0,0,1,2,100,1213,0,0
1,15739548,0,22,7,2,8,4,0,0,0,0,0,2,160,1,0,0
2,15662854,0,29,1,1,4,4,1,0,0,0,1,2,280,1,0,1
3,15687688,0,21,11,1,5,3,0,1,1,11,1,2,0,1,1,0
4,15715750,1,20,8,2,6,4,1,1,1,14,0,2,60,159,1,0

## Let's divide into dependent(A1 to A14) and independent variable(Class)

In [4]:
customers = dataset.iloc[:, 1:-1]
is_fraud = dataset.iloc[:, -1]

In [5]:
customers.head()

   A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13   A14  Class1
0   1  22  11   2   4   4   1   0   0    0    1    2  100  1213       0
1   0  22   7   2   8   4   0   0   0    0    0    2  160     1       0
2   0  29   1   1   4   4   1   0   0    0    1    2  280     1       0
3   0  21  11   1   5   3   0   1   1   11    1    2    0     1       1
4   1  20   8   2   6   4   1   1   1   14    0    2   60   159       1

In [6]:
is_fraud[0:5]

0    0
1    0
2    1
3    0
4    0
Name: fraud, dtype: int64

## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Customers = sc.fit_transform(customers)

In [8]:
np.random.seed(8)
tf.random.set_seed(8)

# Part 2 - Building the ANN
### Initializing the ANN

In [9]:
classifier = Sequential()

### Adding the input layer and the hidden layer

In [10]:
classifier.add(Dense(units=2, kernel_initializer='uniform', activation='relu', input_shape=(15,)))

### Adding the output layer

In [11]:
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

### Compiling the ANN

In [12]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

### Fitting the ANN

In [13]:
classifier.fit(customers, is_fraud, batch_size=1, epochs=2)

Epoch 1/2
690/690 [==============================] - 1s 985us/step - loss: 0.3488 - accuracy: 0.9760
Epoch 2/2
690/690 [==============================] - 1s 952us/step - loss: 0.1807 - accuracy: 0.9681

# Part 3 - making prediction (probability of fraudlent)

In [14]:
y_pred = classifier.predict(customers)

### concatenate with the customersid so we can identify the customer

In [15]:
y_pred = np.concatenate((dataset.iloc[:,0:1].values, y_pred), axis=1)

### let's sort the risk probability

In [16]:
y_pred = y_pred[y_pred[:,1].argsort()]

In [17]:
result = pd.DataFrame(y_pred)

In [18]:
result.columns = ['CustomerID', 'Fraudlent probability']

In [19]:
result.head()

   CustomerID  Fraudlent probability
0  15762716.0           0.000000e+00
1  15598802.0           0.000000e+00
2  15790113.0           0.000000e+00
3  15664615.0           1.471650e-28
4  15708714.0           1.219661e-24

In [20]:
result.tail()

     CustomerID  Fraudlent probability
685  15583067.0               0.142940
686  15611682.0               0.146532
687  15737627.0               0.148385
688  15615296.0               0.156871
689  15752344.0               0.189321